#! /bin/sh


# Startup
#bash ~/.config/bspwm/clean &
killall -q synergy
killall -q synergys


bash ~/.config/polybar/launch.sh &


# Sxhkd
#pgrep -x sxhkd > /dev/null || sxhkd &
while :; do
    if pgrep -x sxhkd > /dev/null; then
        true
    else
        sxhkd &
    fi
    sleep 5
done &


# Monitor Config
bspc monitor DP-2 -d 1 2 3 4 5 6
bspc monitor DP-3 -d 7 8 9 10

bspc desktop -f ^1

bspc config border_width         1
bspc config top_padding         34
bspc config window_gap           6
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config focus_follows_pointer true
bspc config remove_disabled_monitor true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config focused_border_color #81A1C1
bspc config active_border_color #81A1C1
bspc config normal_border_color #4C566A

# Pointer actions when pressing mod + button

bspc config pointer_action1         move
bspc config pointer_action2         resize_side
bspc config pointer_action3         resize_corner

# Mouse

bspc config pointer_modifier mod4
bspc config pointer_action3 resize_side
bspc config pointer_action3 resize_corner
bspc config pointer_action1 move



# Cleanup
bspc rule -r '*'

#Rules
#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Brave-browser desktop='^2' follow=on
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
bspc rule -a Thunar desktop='^3' follow=on
bspc rule -a Pavucontrol state=floating center=true follow=on manage=true
#bspc rule -a Yad state=floating
bspc rule -a Synergy desktop='^10'

##Startup

#Picom
picom --config ~/.config/picom/picom.conf &

# set keyboard
#xsetroot -layout us

#Notification Daemon
#exec_always --no-startup-id dunst &
dunst &

#Screencapture
flameshot &

#User control
lxpolkit &

#Player control
playerctld daemon &

# wallpaper
feh --bg-fill ~/.config/bspwm/background/bg.jpg &

# Blur background
~/.config/feh-blur -b 4 -d &

# Synergy
synergy &












