#! /bin/bash

APPS=(
        synergys
        synergy
)

KILL=(
        synergys
        synergy
)

# First kill lingering apps
for app in "${APPS[@]}"
do
    kill -9 $(pidof $app)
done

for app in "${KILL[@]}"
do
    kill -9 $(pidof $app)
    while _is_running $app; do sleep 1; done
done

# Start new instances
#for app in "${APPS[@]}"
#do
#    env $app ${@:2} &
#done

