#! /bin/sh

xrandr --output DP-3 --mode 1920x1080 --right-of DP-2

internal_monitor=DP-2
external_monitor=DP-3



monitor_add() {
	desktops=4 # How many desktops to move to the second monitor

	for desktop in $(bspc query -D -m $internal_monitor | sed "$desktops"q)
  do
		bspc desktop $desktop --to-monitor $external_monitor
  done

  # Remove "Desktop" created by bspwm
  bspc desktop Desktop --remove
}

monitor_add

#$HOME/.config/polybar/launch.sh

# Terminate already running bar instances
killall -q polybar
#killall -q synergys
# Wait until the processes have been shut down
while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

polybar -r base &
polybar -r ext &
echo "Polybar launched..."
